apiVersion: apps/v1
kind: Deployment
metadata:
  name: flask-k8s-deployment
spec:
  selector:
    matchLabels:
      app: flask-k8s
  template:
    metadata:
      labels:
        app: flask-k8s
    spec:
      schedulerName: pros
      containers:
        - name: flask-k8s
          image: sina88/webserv:latest
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 5000
